apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: kong-observability
  namespace: argocd
spec:
  description: Kong Observability stack deployments
  sourceRepos:
    - "https://github.com/debugnin/kong-observability-gitops"
    - "https://grafana.github.io/helm-charts"
    - "https://prometheus-community.github.io/helm-charts"
    - "https://jaegertracing.github.io/helm-charts"
    - "https://open-telemetry.github.io/opentelemetry-helm-charts"
    - "https://charts.jetstack.io"
  destinations:
    - namespace: "kong-observability"
      server: https://kubernetes.default.svc
    - namespace: argocd
      server: https://kubernetes.default.svc

  clusterResourceWhitelist:
    - group: ""
      kind: Namespace
    - group: apiextensions.k8s.io
      kind: CustomResourceDefinition
    - group: rbac.authorization.k8s.io
      kind: ClusterRole
    - group: rbac.authorization.k8s.io
      kind: ClusterRoleBinding
    - group: admissionregistration.k8s.io
      kind: ValidatingWebhookConfiguration
    - group: admissionregistration.k8s.io
      kind: MutatingWebhookConfiguration
    - group: cert-manager.io
      kind: ClusterIssuer
  namespaceResourceWhitelist:
    - group: ""
      kind: "*"
    - group: apps
      kind: "*"
    - group: networking.k8s.io
      kind: "*"
    - group: argoproj.io
      kind: Application
    - group: rbac.authorization.k8s.io
      kind: "*"
    - group: autoscaling
      kind: "*"
    - group: cert-manager.io
      kind: "*"
    - group: batch
      kind: "*"
    - group: monitoring.coreos.com
      kind: "*"
  roles:
    - name: admin
      policies:
        - p, proj:kong-observability:admin, applications, *, kong-observability/*, allow
      groups:
        - kong-admins