apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: fluent-bit
  namespace: argocd
spec:
  project: kong-observability
  source:
    repoURL: https://fluent.github.io/helm-charts
    chart: fluent-bit
    targetRevision: 0.47.10
    helm:
      releaseName: fluent-bit
      values: |
        kind: DaemonSet
        replicaCount: 1

        image:
          repository: fluent/fluent-bit
          tag: 3.1.9
          pullPolicy: IfNotPresent

        serviceAccount:
          create: true

        rbac:
          create: true
          nodeAccess: true

        extraPorts:
          - name: http-input
            containerPort: 2021
            protocol: TCP

        config:
          service: |
            [SERVICE]
                Daemon Off
                Flush 1
                Log_Level info
                Parsers_File /fluent-bit/etc/parsers.conf
                Parsers_File /fluent-bit/etc/conf/custom_parsers.conf
                HTTP_Server On
                HTTP_Listen 0.0.0.0
                HTTP_Port 2020
                Health_Check On
          
          inputs: |
            [INPUT]
                Name tail
                Path /var/log/containers/*.log
                multiline.parser docker, cri
                Tag kube.*
                Mem_Buf_Limit 50MB
                Skip_Long_Lines On
            
            [INPUT]
                Name http
                Listen 0.0.0.0
                Port 2021
                Tag kong.http
          
          filters: |
            [FILTER]
                Name kubernetes
                Match kube.*
                Kube_URL https://kubernetes.default.svc:443
                Kube_CA_File /var/run/secrets/kubernetes.io/serviceaccount/ca.crt
                Kube_Token_File /var/run/secrets/kubernetes.io/serviceaccount/token
                Kube_Tag_Prefix kube.var.log.containers.
                Merge_Log On
                Keep_Log Off
                K8S-Logging.Parser On
                K8S-Logging.Exclude Off
          
          outputs: |
            [OUTPUT]
                Name opentelemetry
                Match *
                Host otel-collector-opentelemetry-collector.kong-observability.svc.cluster.local
                Port 4318
                logs_uri /v1/logs
                log_response_payload true
                tls off
                logs_body_key $message
                logs_trace_id_message_key traceid
                logs_span_id_message_key spanid

        tolerations:
          - key: node-role.kubernetes.io/control-plane
            operator: Exists
            effect: NoSchedule
          - key: node-role.kubernetes.io/master
            operator: Exists
            effect: NoSchedule

        resources:
          limits:
            cpu: 100m
            memory: 128Mi
          requests:
            cpu: 100m
            memory: 128Mi
  destination:
    server: https://kubernetes.default.svc
    namespace: kong-observability
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
