apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: grafana-agent
  namespace: argocd
spec:
  project: kong-observability
  source:
    repoURL: https://grafana.github.io/helm-charts
    chart: grafana-agent-operator
    targetRevision: 0.3.21
    helm:
      releaseName: grafana-agent-operator
      values: |
        image:
          registry: ghcr.io
          repository: grafana/agent-operator
          tag: v0.40.4
        resources:
          limits:
            cpu: 100m
            memory: 128Mi
          requests:
            cpu: 100m
            memory: 128Mi
  destination:
    server: https://kubernetes.default.svc
    namespace: kong-observability
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true