apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: loki
  namespace: argocd
spec:
  project: kong-observability
  source:
    repoURL: https://grafana.github.io/helm-charts
    chart: loki
    targetRevision: 6.43.0
    helm:
      releaseName: loki
      skipCrds: true
      values: |
        # Loki deployment configuration
        deploymentMode: SingleBinary
        singleBinary:
          replicas: 1

        loki:
          auth_enabled: false
          commonConfig:
            replication_factor: 1
          useTestSchema: true

        querier:
          max_concurrent: 2

        # Optional: Simplify MinIO (local object store)
        lokiStorage:
          type: filesystem

        # Use a specific image tag if desired
        image:
          tag: 3.5.3

        # Disable self-monitoring features that rely on Grafana Agent
        monitoring:
          dashboards:
            enabled: false
          serviceMonitor:
            enabled: false
          rules:
            enabled: false
          selfMonitoring:
            enabled: false
            grafanaAgent:
              installOperator: false
        
        # Disable all Grafana Agent components
        grafanaAgent:
          enabled: false
  destination:
    server: https://kubernetes.default.svc
    namespace: kong-observability
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
