apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: loki
  namespace: argocd
spec:
  project: kong-observability
  source:
    repoURL: https://grafana.github.io/helm-charts
    chart: loki
    targetRevision: 5.41.4
    helm:
      releaseName: loki
      skipCrds: true
      values: |
        deploymentMode: SingleBinary
        singleBinary:
          replicas: 1
        loki:
          auth_enabled: false
          commonConfig:
            replication_factor: 1
          useTestSchema: true
        querier:
          max_concurrent: 2
        image:
          tag: 3.5.3
  destination:
    server: https://kubernetes.default.svc
    namespace: kong-observability
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
