apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: otel-collector
  namespace: argocd
spec:
  project: kong-observability
  source:
    repoURL: https://open-telemetry.github.io/opentelemetry-helm-charts
    chart: opentelemetry-collector
    targetRevision: 0.136.1
    helm:
      releaseName: otel-collector
      values: |
        mode: deployment
        image:
          repository: otel/opentelemetry-collector-contrib
          tag: 0.136.0
          pullPolicy: IfNotPresent
        clusterRole:
          create: true
          rules:
            - apiGroups: [""]
              resources: ["pods", "services", "endpoints", "nodes"]
              verbs: ["get", "list", "watch"]
            - apiGroups: [""]
              resources: ["namespaces"]
              verbs: ["get", "list", "watch"]
        ports:
          prometheus:
            enabled: true
            containerPort: 8889
            servicePort: 8889
            protocol: TCP
        config:
          receivers:
            otlp:
              protocols:
                grpc:
                  endpoint: 0.0.0.0:4317
                http:
                  endpoint: 0.0.0.0:4318
            prometheus:
              config:
                scrape_configs:
                  - job_name: 'kong-gateway'
                    metrics_path: /metrics
                    kubernetes_sd_configs:
                      - role: pod
                        namespaces:
                          names:
                            - kong-anz
                            - kong-cba
                            - kong-nab
                    relabel_configs:
                      - source_labels: [__meta_kubernetes_pod_label_app_kubernetes_io_name]
                        regex: kong
                        action: keep
                      - source_labels: [__meta_kubernetes_pod_container_port_name]
                        regex: status
                        action: keep
                      - source_labels: [__meta_kubernetes_pod_name]
                        target_label: instance
                        action: replace
          processors:
            batch: {}
          exporters:
            otlp/jaeger:
              endpoint: jaeger-collector.kong-observability.svc.cluster.local:4317
              tls:
                insecure: true
            otlphttp/loki:
              endpoint: http://loki.kong-observability.svc.cluster.local:3100/otlp
            prometheus:
              endpoint: "0.0.0.0:8889"
            debug:
              verbosity: detailed
          service:
            pipelines:
              traces:
                receivers: [otlp]
                processors: [batch]
                exporters: [otlp/jaeger, debug]
              logs:
                receivers: [otlp]
                processors: [batch]
                exporters: [otlphttp/loki]
              metrics:
                receivers: [prometheus]
                processors: [batch]
                exporters: [prometheus]

  destination:
    server: https://kubernetes.default.svc
    namespace: kong-observability
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
