apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: otel-collector
  namespace: argocd
spec:
  project: kong-observability
  source:
    repoURL: https://open-telemetry.github.io/opentelemetry-helm-charts
    chart: opentelemetry-collector
    targetRevision: 0.74.0
    helm:
      releaseName: otel-collector
      values: |
        mode: deployment
        config:
          receivers:
            otlp:
              protocols:
                grpc:
                  endpoint: 0.0.0.0:4317
                http:
                  endpoint: 0.0.0.0:4318
          processors:
            batch: {}
          exporters:
            jaeger:
              endpoint: jaeger-collector:14250
              tls:
                insecure: true
            prometheus:
              endpoint: "0.0.0.0:8889"
            loki:
              endpoint: http://loki:3100/loki/api/v1/push
          service:
            pipelines:
              traces:
                receivers: [otlp]
                processors: [batch]
                exporters: [jaeger]
              metrics:
                receivers: [otlp]
                processors: [batch]
                exporters: [prometheus]
              logs:
                receivers: [otlp]
                processors: [batch]
                exporters: [loki]
  destination:
    server: https://kubernetes.default.svc
    namespace: kong-observability
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true