apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: otel-collector
  namespace: argocd
spec:
  project: kong-observability
  source:
    repoURL: https://open-telemetry.github.io/opentelemetry-helm-charts
    chart: opentelemetry-collector
    targetRevision: 0.136.1
    helm:
      releaseName: otel-collector
      values: |
        mode: deployment
        image:
          repository: otel/opentelemetry-collector-contrib
          tag: 0.136.0  # or match the chart version (check https://hub.docker.com/r/otel/opentelemetry-collector-contrib/tags)
          pullPolicy: IfNotPresent
        config:
          receivers:
            otlp:
              protocols:
                grpc:
                  endpoint: 0.0.0.0:4317
                http:
                  endpoint: 0.0.0.0:4318
            prometheus:
              config:
                scrape_configs:
                  - job_name: 'kong-gateway'
                    metrics_path: /metrics
                    kubernetes_sd_configs:
                    - role: pod
                      namespaces:
                        names:
                        - kong-anz
                        - kong-cba
                        - kong-nab
                      selectors:
                        - role: "pod"
                          label: "app.kubernetes.io/name=kong"
                    relabel_configs:
                    - source_labels: [ __meta_kubernetes_pod_container_port_name ]
                      regex: 'status'
                      action: keep
                    - source_labels: [ __meta_kubernetes_pod_name ]
                      action: replace
                      target_label: instance
          processors:
            batch: {}
          exporters:
            otlp/jaeger:
              endpoint: jaeger-collector:4317
              tls:
                insecure: true
            otlphttp/loki:
              endpoint: http://loki:3100/otlp/v1/logs
            prometheusremotewrite:
              endpoint: http://prometheus-server.kong-observability.svc:80/api/v1/write
            debug:
              verbosity: detailed
          service:
            pipelines:
              traces:
                receivers: [otlp]
                processors: [batch]
                exporters: [otlp/jaeger, debug]
              logs:
                receivers: [otlp]
                processors: [batch]
                exporters: [otlphttp/loki, debug]
              metrics:
                receivers: [prometheus]
                processors: [batch]
                exporters: [prometheusremotewrite, debug]
  destination:
    server: https://kubernetes.default.svc
    namespace: kong-observability
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
