apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: prometheus
  namespace: argocd
spec:
  project: kong-observability
  source:
    repoURL: https://prometheus-community.github.io/helm-charts
    chart: prometheus
    targetRevision: 25.27.0
    helm:
      releaseName: prometheus
      values: |
        server:
          persistentVolume:
            enabled: true
            storageClass: standard
            accessModes:
              - ReadWriteOnce
            size: 10Gi
          retention: "15d"
        serverFiles:
          prometheus.yml:
            scrape_configs:
              - job_name: 'otel-collector'
                scrape_interval: 5s
                static_configs:
                  - targets: ['otel-collector-opentelemetry-collector.kong-observability.svc.cluster.local:8889']
        alertmanager:
          enabled: true
          persistentVolume:
            enabled: true
            storageClass: standard
            accessModes:
              - ReadWriteOnce
            size: 2Gi
        pushgateway:
          enabled: false
        kube-state-metrics:
          enabled: true
        prometheus-node-exporter:
          enabled: true
  destination:
    server: https://kubernetes.default.svc
    namespace: kong-observability
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
